# Generated by Django 5.1.3 on 2024-12-05 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_is_active_parentalconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent_approved', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ParentalConsent',
        ),
    ]
