# docker-compose.yml

services:
  db:
    image: postgres:15
    # Load environment variables from the backend .env.local
    env_file: ./backend/.env.local
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # Adjust this if you want a data volume or a local directory.
      - ./postgres:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
    # Run the server on 0.0.0.0:8000 inside container
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./backend/.env.local
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
