version: "3.8"

services:
  db:
    image: postgres:15
    env_file: ./backend/.env.local
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
      - ./backend/.env.local
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge
