# Generated by Django 5.1.3 on 2024-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parentconsent_delete_parentalconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('rs', 'Serbian')], default='en', max_length=10),
        ),
    ]
